[package]
name = "llm"
version = "0.0.1"
authors = ["Jim Wang <jimw@wxyz.cc>"]
edition = "2024"

[pylib]
name = "llm"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version >= "0.21.0", features = ["extension-module", "abi3-py39"] }
numpy = { version >= "0.21.0" }

[workspace]
